apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;

    events {
        worker_connections 1024;
    }

    http {
        log_format custom '$remote_addr - $host [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" "$http_user_agent" '
                          '$http_x_forwarded_for $http_x_real_ip $http_x_forwarded_proto';
        access_log /var/log/nginx/access.log custom;
        sendfile on;

        upstream openfaas {
            server gateway.openfaas.svc.cluster.local:8080;
        }

        server {
            listen 80;

            location / {
                proxy_pass http://openfaas;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }

