version: "3.8"

services:
  gateway:
    image: openfaas/gateway:t6
    networks:
      - openfaas
    environment:
      - direct_functions=false
      - read_timeout=60s
      - write_timeout=60s
      - upstream_timeout=65s
      - faas_nats_address=nats
      - faas_nats_port=4222
    ports:
      - "31112:8080"

  nginx:
    image: nginx:latest
    networks:
      - openfaas
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  tcpdump:
    image: dockersec/tcpdump:latest
    platform: linux/arm64
    networks:
      - openfaas
    command: ["tcpdump -i eth0"]
    entrypoint: ["/bin/sh", "-c"]
    volumes:
      - /tmp:/tmp

networks:
  openfaas:
    driver: bridge

